import dotenv from "dotenv";
dotenv.config();

import express from "express";
import axios from "axios";
import cors from "cors";

const app = express();

const allowedOrigins = [
  "https://chef-claude-pi-nine.vercel.app",
  "http://localhost:5173",
];

app.use(
  cors({
    origin: allowedOrigins,
    methods: ["GET", "POST", "OPTIONS"],
    allowedHeaders: ["Content-type", "Authorization"],
    credentials: true,
  })
);

app.use(express.json());

app.get("/", (req, res) => {
  res.send("Chef Claude API online 🍳");
});

const PORT = process.env.PORT || 3001;

app.post("/api/recipe", async (req, res) => {
  const { ingredients } = req.body;

  if (!ingredients || !Array.isArray(ingredients)) {
    return res.status(400).json({ error: "Invalid ingredients format" });
  }

  try {
    console.log("🧾 Request received with ingredients:", ingredients);

    const response = await axios.post(
      "https://api-inference.huggingface.co/models/HuggingFaceH4/zephyr-7b-beta",
      {
        inputs: `Make a recipe with: ${ingredients.join(", ")}`,
        parameters: { max_new_tokens: 512 },
      },
      {
        headers: {
          Authorization: `Bearer ${process.env.HF_ACCESS_TOKEN}`,
        },
        timeout: 100000,
      }
    );
    console.log(response.data);

    const recipe = response.data[0]?.generated_text || "No recipe found";

    if (!recipe) {
      throw new Error("No recipe generated by the model.");
    }

    res.json({ recipe });
  } catch (error) {
    console.error(
      "Error when searching for recipe:",
      error?.response?.data || error.message
    );
    res.status(500).json({ error: "Error when searching for recipe" });
  }
});

app.listen(PORT, () => {
  console.log(`Server runnig in: ${PORT}`);
});
